name: Deploy to Firebase (main -> dev)
on:
  push:
    branches:
      - main
concurrency: development
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: development
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./service-account.json
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Restore service account
        run: |
          echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }} | base64 --decode > service-account.json

      - name: Build app
        run: |
          npm install
          npm run build
        env:
          VITE_SUMTIMER_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_SUMTIMER_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VITE_SUMTIMER_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VITE_SUMTIMER_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          VITE_SUMTIMER_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          VITE_SUMTIMER_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          VITE_SUMTIMER_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

      - name: Setup functions
        working-directory: ./functions
        run: npm install

      - name: Deploy to Firebase
        working-directory: ./
        run: npm run deploy -- --project ${{ secrets.FIREBASE_PROJECT_ID }} --force
